import type { Activity, MonthlyStats } from './types'

export const mockActivities: Activity[] = [
  {
    id: '1',
    date: '2026-01-05',
    type: 'training',
    title: '개인 드리블 훈련',
    location: '서울 풋살파크',
    weather: 'sunny',
    trainingTopic: '1대1 드리블 돌파',
    lessonsLearned: '몸의 무게중심을 낮추고 상대의 무게중심을 읽는 연습',
    effortScore: 4,
    kpt: {
      keep: '공을 가까이 두는 습관',
      problem: '왼발 사용 빈도가 낮음',
      try: '왼발 드리블 연습 추가',
    },
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-01-05T10:00:00Z',
  },
  {
    id: '2',
    date: '2026-01-08',
    type: 'match',
    title: '플랩풋볼 소셜매치',
    location: '강남 풋살장',
    matchType: 'plab',
    result: 'win',
    score: { team: 5, opponent: 3 },
    personalStats: { goals: 2, assists: 1 },
    goodPoints: '적극적인 전방 압박, 동료와의 호흡',
    badPoints: '후반 체력 저하',
    tacticalNotes: '4-0 포메이션에서 피봇 역할 수행',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    comments: [
      {
        id: 'c1',
        timestamp: 45,
        content: '이 장면에서 공간 만들기 좋았어!',
        authorId: 'user1',
        authorName: '김민수',
        createdAt: '2026-01-08T20:00:00Z',
      },
      {
        id: 'c2',
        timestamp: 120,
        content: '득점 장면! 왼발 슛 연습한 보람 있네',
        authorId: 'me',
        authorName: '나',
        createdAt: '2026-01-08T20:05:00Z',
      },
      {
        id: 'c3',
        timestamp: 180,
        content: '@홍길동 여기서 패스 타이밍 좋았어',
        authorId: 'user2',
        authorName: '이영희',
        mentions: ['홍길동'],
        createdAt: '2026-01-08T20:10:00Z',
      },
    ],
    createdAt: '2026-01-08T18:00:00Z',
    updatedAt: '2026-01-08T18:00:00Z',
  },
  {
    id: '3',
    date: '2026-01-12',
    type: 'training',
    title: '팀 전술 훈련',
    location: '용산 풋살센터',
    weather: 'cloudy',
    trainingTopic: '공격 시 움직임과 수비 전환',
    lessonsLearned: '역습 상황에서 빠른 위치 선점의 중요성',
    effortScore: 5,
    kpt: {
      keep: '빠른 판단력',
      problem: '체력 분배가 고르지 않음',
      try: '인터벌 트레이닝 병행',
    },
    createdAt: '2026-01-12T14:00:00Z',
    updatedAt: '2026-01-12T14:00:00Z',
  },
  {
    id: '4',
    date: '2026-01-15',
    type: 'match',
    title: '사내 대회 준결승',
    location: '마포 풋살아레나',
    matchType: 'tournament',
    result: 'win',
    score: { team: 3, opponent: 2 },
    personalStats: { goals: 1, assists: 2 },
    goodPoints: '결정적 순간 침착한 패스',
    badPoints: '전반 슈팅 정확도 부족',
    tacticalNotes: '3-1 포메이션, 공격형 미드필더',
    createdAt: '2026-01-15T19:00:00Z',
    updatedAt: '2026-01-15T19:00:00Z',
  },
  {
    id: '5',
    date: '2026-01-18',
    type: 'plab',
    title: '플랩풋볼 6vs6',
    location: '홍대 플랩파크',
    matchType: 'plab',
    result: 'win',
    score: { team: 6, opponent: 4 },
    personalStats: { goals: 2, assists: 1 },
    goodPoints: '빠른 전환 플레이',
    badPoints: '수비 복귀 늦음',
    createdAt: '2026-01-18T21:00:00Z',
    updatedAt: '2026-01-18T21:00:00Z',
  },
  {
    id: '6',
    date: '2026-01-20',
    type: 'plab',
    title: '플랩풋볼 소셜매치',
    location: '강남 플랩파크',
    matchType: 'plab',
    result: 'lose',
    score: { team: 2, opponent: 5 },
    personalStats: { goals: 0, assists: 1 },
    goodPoints: '포기하지 않는 자세',
    badPoints: '컨디션 난조',
    createdAt: '2026-01-20T19:00:00Z',
    updatedAt: '2026-01-20T19:00:00Z',
  },
  {
    id: '7',
    date: '2026-01-22',
    type: 'training',
    title: '슈팅 연습',
    location: '서울 풋살파크',
    weather: 'sunny',
    trainingTopic: '다양한 각도에서의 슈팅',
    lessonsLearned: '공의 중심을 정확히 맞추는 것이 핵심',
    effortScore: 4,
    kpt: {
      keep: '인스텝 슛 정확도',
      problem: '토킥 습관',
      try: '의식적으로 인스텝 사용',
    },
    createdAt: '2026-01-22T16:00:00Z',
    updatedAt: '2026-01-22T16:00:00Z',
  },
  {
    id: '8',
    date: '2026-01-25',
    type: 'match',
    title: '플랩풋볼 소셜매치',
    location: '잠실 풋살장',
    matchType: 'plab',
    result: 'draw',
    score: { team: 4, opponent: 4 },
    personalStats: { goals: 1, assists: 0 },
    goodPoints: '수비 가담 적극적',
    badPoints: '패스 미스 다수',
    createdAt: '2026-01-25T18:00:00Z',
    updatedAt: '2026-01-25T18:00:00Z',
  },
  {
    id: '9',
    date: '2026-01-28',
    type: 'training',
    title: '체력 훈련',
    location: '올림픽공원',
    weather: 'cold',
    trainingTopic: '지구력 향상을 위한 인터벌',
    lessonsLearned: '꾸준한 체력 관리가 경기력에 직결',
    effortScore: 5,
    kpt: {
      keep: '끝까지 포기하지 않는 자세',
      problem: '초반 페이스 조절 실패',
      try: '심박수 기반 훈련 적용',
    },
    createdAt: '2026-01-28T07:00:00Z',
    updatedAt: '2026-01-28T07:00:00Z',
  },
]

export const mockMonthlyStats: MonthlyStats = {
  month: '2026-01',
  totalActivities: 9,
  trainingCount: 4,
  matchCount: 3,
  totalGoals: 4,
  totalAssists: 3,
  avgEffortScore: 4.5,
}

export function getActivitiesByDate(date: string): Activity[] {
  return mockActivities.filter((a) => a.date === date)
}

export function getActivitiesByMonth(year: number, month: number): Activity[] {
  const monthStr = `${year}-${String(month).padStart(2, '0')}`
  return mockActivities.filter((a) => a.date.startsWith(monthStr))
}

export function getActivityById(id: string): Activity | undefined {
  return mockActivities.find((a) => a.id === id)
}
